### ISSUE TITLE
动效章节配图有误

### ISSUE THREAD

**Issue by jimmywzm** [zdhxiong/Material-Design-Chinese#2]
动效 > 时长&缓动 > 加速曲线 的配图使用了夏普曲线的配图

加速曲线的图应该是这样的：
![2017-06-27 9 12 16](https://user-images.githubusercontent.com/1926138/27566591-d291b5a2-5b18-11e7-8ca2-255fac06a327.png)

**Comment by zdhxiong** [comment]
已修复
