### ISSUE TITLE
 项目还在继续进行吗？

### ISSUE THREAD

**Issue by zuohuadong** [zdhxiong/Material-Design-Chinese#22]
我们想参与翻译

**Comment by zdhxiong** [comment]
在继续
我个人因为工作忙比较久没翻译，不过还是可以每天处理 pr 的。

**Comment by zuohuadong** [comment]
> 在继续
> 我个人因为工作忙比较久没翻译，不过还是可以每天处理 pr 的。

https://www.mdui.org/design     这里还是 v1  么。

md 文件中看到 一堆html 相关的东西。还有 php 的环境...

为什么不基于这两个呢
https://github.com/facebook/Docusaurus
https://github.com/docsifyjs/docsify

**Comment by zdhxiong** [comment]
网站上还是 v1。

因为文档里面包含大量的图片和视频，和传统的技术文档不同。而且我希望生成的 html 文档样式上也符合 Material Design 规范，所以选择自己写编译脚本。md 文档里的 html 是为了能通过写 CSS 来对图片和视频进行排版。

**Comment by zuohuadong** [comment]
> 网站上还是 v1。
> 
> 因为文档里面包含大量的图片和视频，和传统的技术文档不同。而且我希望生成的 html 文档样式上也符合 Material Design 规范，所以选择自己写编译脚本。md 文档里的 html 是为了能通过写 CSS 来对图片和视频进行排版。

那可以用node 做生成啊，而且 webpack 还有很多工具能编译和压缩。

**Comment by zdhxiong** [comment]
重点是 markdown 文件的翻译，你当然可以自己写 node 脚本来生成。

**Comment by zuohuadong** [comment]
> 重点是 markdown 文件的翻译，你当然可以自己写 node 脚本来生成。

打算用node 重构下，并且压缩下生成后的html。

markdown 这个你是怎么拉取的？ 手工吗？ 现在如何同步到最新 （我看最近有更新记录）

**Comment by zdhxiong** [comment]
手工整理的。
更新也是下载原始文档后比较差异，手工更新过来的。

**Comment by zuohuadong** [comment]
方便加个微信么？  
最近想和几个同事一起翻译。

z2858258

**Comment by zdhxiong** [comment]
这是上次更新时的文档备份：https://github.com/zdhxiong/material.io-design
这是最新的文档：https://material.io/design/

**Comment by zuohuadong** [comment]
垃圾php~
